export const skills = {
    heading: "Skills",
    quote: "Build your skills, not your resume",
    techSkills: [
        "JavaScript",
        "NodeJS",
        "ReactJS",
        "React Native",
        // "Redux",
        // "C++",
        // "C#",
        // "C",
        "Java",
        "Python",
        "HTML",
        "CSS",
        // "jQuery",
        // "Bootstrap",
        // "Material Design",
        // "MaterializeCSS",
        // "Git",
        "GitHub",
        // "MongoDB",
    ],
    industryKnowledge: [
        "Software",
        "Google Analytics",
        "Machine Learning",
        "Data Analysis",
        "Data Science",
        // "Marketing",
        // "Publicity",
        // "Blogging",
        "Content Writing",
        "Creative Writing",
        // "Web Content",
        // "Frontend",
        "Backend",
        // "Design",
        // "Web",
        "Android"
    ],
    interpersonalSkills: [
        "Communication",
        "Teaching",
        "Time Management",
        "Leadership",
        "Management"
    ]
};